variable "ResourceGroupName" {}
variable "ResourceGroupLocation" {}
variable "StorageAccountName" {}
variable "AppServicePlanName" {}
variable "FunctionAppName" {}
variable "subscription_id" {}
variable "tenant_id" {}
variable "client_id" {}
variable "client_secret" {}